### PR TITLE
Validate elements before submission

### LINKED ISSUE #94: Validate elements before submission
Following #89

Form elements are not currently validated on submission, this can lead to difficult issues where outdated values are passed into the form action. There is currently no straightforward way to workaround this, since the 'submit' event is only triggered on the form block and that 'validate' method does not pull values from the DOM.

(Also I don't think this should be implemented as an option, values passed into 'action' should always correspond to what is actually in the input)

### PR DESCRIPTION
**Pull request by ramijarrar**
Resolves #94

### CODE REVIEW

**Comment by ramijarrar** [comment]
@jonjamz Does that look good to you? After this is merged I will follow-up with a PR that addresses the default validation on startup.

**Comment by ramijarrar** [comment]
@jonjamz Have you had a chance to take a look at this yet?

**Comment by jonjamz** [comment]
@ramijarrar sorry about that. This looks good. Smart to use `Blaze.getView`.

**Comment by davidecantini** [comment]
@jonjamz Can you release a minor new version (2.1.3?) to include this? Thanks in advance.

**Comment by jonjamz** [comment]
Done!

**Comment by davidecantini** [comment]
Thanks. Unfortunately, the new code generates an exception on submit:

Here is the stack trace:
==================
_templates_forms.js?hash=67d434e…:758 Uncaught TypeError: Blaze.getView(...).templateInstance is not a function
(anonymous function)	@	templates_forms.js?hash=67d434e…:758
component.submit	@	templates_forms.js?hash=67d434e…:757
evt.submit form	@	templates_forms.js?hash=67d434e…:1628
(anonymous function)	@	blaze.js?hash=38069f4…:3708
Template._withTemplateInstanceFunc	@	blaze.js?hash=38069f4…:3677
(anonymous function)	@	blaze.js?hash=38069f4…:3707
(anonymous function)	@	blaze.js?hash=38069f4…:2550
Blaze._withCurrentView	@	blaze.js?hash=38069f4…:2204
(anonymous function)	@	blaze.js?hash=38069f4…:2549
(anonymous function)	@	blaze.js?hash=38069f4…:825
jQuery.event.dispatch	@	jquery.js?hash=649d9f4…:4707

==================

The code involved is this line:
`var instance = Blaze.getView(element).templateInstance(); `

**Comment by davidecantini** [comment]
@jonjamz While you or @ramijarrar are looking into the issue reported, could you please tag version 2.1.2 (the latest working)? That would be of great help as right now, the upgrade broke the code and cannot install the previously version. Thank you so much.

**Comment by jonjamz** [comment]
`v2.1.2` is tagged. I'm on a train right now and logged in via hotspot. I may revert the changes in a `v2.1.4` release, what do you think @davidecantini?

**Comment by davidecantini** [comment]
Yes, please. 
Also because I'm trying to install 2.1.2 but still get 2.1.3?
```
> meteor add templates:forms@2.1.2
                                              
Changes to your project's package version selections:
                                              
templates:forms  added, version 2.1.3 
```
Thanks for fixing this as soon as possible.

**Comment by jonjamz** [comment]
Alright `2.1.4` is published.

**Comment by ramijarrar** [comment]
I've tested with a pretty form heavy app before committing and version 2.1.3 isn't causing any errors for me. Can you elaborate more on the specific form that caused this? Also, what version of Meteor are you running on?

**Comment by davidecantini** [comment]
@jonjamz Thank you.

**Comment by davidecantini** [comment]
@ramijarrar:
I'm using Meteor 1.3.1. Here is the content of .meteor/versions:
----------------
accounts-base@1.2.5
accounts-password@1.1.7
accounts-ui@1.1.8
accounts-ui-unstyled@1.1.11
alanning:roles@1.2.15
aldeed:simple-schema@1.5.3
allow-deny@1.0.3
amplify@1.0.0
autoupdate@1.2.7
babel-compiler@6.6.1
babel-runtime@0.1.7
base64@1.0.7
binary-heap@1.0.7
blaze@2.1.6
blaze-html-templates@1.0.3
blaze-tools@1.0.7
boilerplate-generator@1.0.7
caching-compiler@1.0.3
caching-html-compiler@1.0.5
callback-hook@1.0.7
cfs:http-methods@0.0.30
check@1.1.3
coffeescript@1.0.16
ddp@1.2.4
ddp-client@1.2.4
ddp-common@1.2.4
ddp-rate-limiter@1.0.3
ddp-server@1.2.5
deps@1.0.11
diff-sequence@1.0.4
ecmascript@0.4.2
ecmascript-runtime@0.2.9
ejson@1.0.10
email@1.0.11
es5-shim@4.5.9
fastclick@1.0.10
fourseven:scss@3.4.1
geojson-utils@1.0.7
hot-code-push@1.0.3
html-tools@1.0.8
htmljs@1.0.8
http@1.1.4
id-map@1.0.6
jquery@1.11.7
kadira:flow-router@2.11.0
launch-screen@1.0.10
less@2.5.7
livedata@1.0.17
localstorage@1.0.8
logging@1.0.11
mdg:validation-error@0.5.1
meteor@1.1.13
meteor-base@1.0.3
meteorspark:util@0.2.0
minifier-css@1.1.10
minifier-js@1.1.10
minimongo@1.0.13
mobile-experience@1.0.3
mobile-status-bar@1.0.11
modules@0.5.2
modules-runtime@0.6.2
mongo@1.1.6
mongo-id@1.0.3
npm-bcrypt@0.7.8_2
npm-mongo@1.4.42
observe-sequence@1.0.10
ordered-dict@1.0.6
promise@0.6.6
raix:eventemitter@0.1.3
random@1.0.8
rate-limit@1.0.3
reactive-dict@1.1.6
reactive-var@1.0.8
reload@1.1.7
retry@1.0.6
routepolicy@1.0.9
service-configuration@1.0.8
session@1.1.4
sha@1.0.6
spacebars@1.0.10
spacebars-compiler@1.0.10
srp@1.0.7
standard-minifier-css@1.0.5
standard-minifier-js@1.0.5
tap:i18n@1.8.0
tap:i18n-ui@0.7.0
templates:forms@2.1.4
templating@1.1.8
templating-tools@1.0.3
tracker@1.0.12
twbs:bootstrap@3.3.6
ui@1.0.10
underscore@1.0.7
url@1.0.8
webapp@1.2.7
webapp-hashing@1.0.8
----------------
Just using a form with some array fields, pretty normal stuff I guess.

**Comment by ramijarrar** [comment]
@davidecantini What's the output of Blaze.getView on one of your form elements?

**Comment by davidecantini** [comment]
If you want me to test that on my environment, please send the html and js snippets and I'll do it within tonight/tomorrow. Thanks

**Comment by ramijarrar** [comment]
Just run ```Blaze.getView(document.getElementById("foo"))```

**Comment by davidecantini** [comment]
None of the form elements has an id, but after adding <input id="foo">, Blaze.getView(document.getElementById("foo")) returns the view, which contains the templateInstance function property.
As expected, the exception reported above may occur only under certain circumstances.

**Comment by ramijarrar** [comment]
@davidecantini Okay thanks for that. Would it be possible for you to create a repro for this?

**Comment by davidecantini** [comment]
Yes, sure. Please manage to have the test version (2.1.3 or whichever you want me to test) installable as follows:
```
> meteor remove templates:forms
> meteor add templates:forms@2.1.3 
```
or in any other way. The important thing is that I can switch back to the working version at any time, smoothly.

**Comment by ramijarrar** [comment]
Yes that will work fine, but you should probably do this in a separate repo i.e not your main app (start with one of the example apps and see if you can recreate the error)

**Comment by davidecantini** [comment]
@ramijarrar reminder:

Please manage to have the test version (2.1.3 or whichever you want me to test) installable as follows:
```
> meteor remove templates:forms
> meteor add templates:forms@2.1.3 
```
Until then I cannot do test to reproduce the issue.

**Comment by ramijarrar** [comment]
@davidecantini To specify an exact constraint, you need to use the ```=``` symbol. Otherwise you are specifying the range of compatible versions higher than 2.1.3 which will always include 2.1.4 (semantic versioning). 

The correct command is:

```bash
meteor add templates:forms@=2.1.3
``` 

You can remove this constraint by running:

```bash
meteor add templates:forms
```

**Comment by davidecantini** [comment]
Thank you. As I'm testing it, I get the error upon submission. With version 2.1.2 (and 2.1.4), everything works well. 
```
        // Issue #94                                                                                               
        formElements = self.findAll(component.elementSelectors.join(', '));                             
        formElements.forEach(function (element) {                                                                  
          var instance = Blaze.getView(element).templateInstance();    <== This causes the exception
```
It would be helpful to instrument the code to have a console.log(element) print on which element the error occur, so it'd be easier to narrow down the issue.

**Comment by ramijarrar** [comment]
I already know what the error is. I have not been able to reproduce this in my projects. Please create a repro so I can look into this (run ```meteor create submission-bug``` and work from there).

**Comment by davidecantini** [comment]
Ok, that's great news. If you know what the error is already, why don't you provide a fixed version, which I can quickly test to confirm that it works? That way we can get the new version fixed within today I guess.

**Comment by ramijarrar** [comment]
@davidecantini Please read the full comment before responding. I know what the error is because you posted it 3 days ago, now the next step is for you to create a repro.

**Comment by davidecantini** [comment]
@ramijarrar you wrote: "Please read the full comment before responding. I know what the error is because you posted it 3 days ago, now the next step is for you to create a repro."

Now you make me wonder if I read it too well, actually. Since you wrote that you know **what** the error is, I thought that you already have a fix. In that case, you could just provide a fixed version for me to quickly test and confirm the fix. 
On the contrary, if all you know so far is *WHERE* the error is in your code but you're not able to reproduce yet, then I'm willing to help you. To do so, I want an instrumented test version where I can see the element that generates the exception, otherwise it could be done but it would take much more time to isolate culprit, and I can't go through that right now.

**Comment by ramijarrar** [comment]
@jonjamz Have you been able to reproduce the issue described by @davidecantini?

**Comment by ramijarrar** [comment]
@davidecantini Makes sense, I added some logging to our fork [here](https://github.com/talos-code/forms) so you can just add that as a local package and it will take precedence (delete it once you are done and everything is restored back to normal). Thanks again for your help with this.

**Comment by paulbalomiri** [comment]
Hi, is it possible that you are using blaze templates as children of non-blaze Elements?

I should check probably that the Blaze.getView() really returns a view. It surely does so if it is generated from within a template html/jade definition.

**Comment by ramijarrar** [comment]
@paulbalomiri Can you try with v2.1.3 and see if you can reproduce the error?

**Comment by ramijarrar** [comment]
@davidecantini Did you get a chance to try your app with the instrumented test version that I linked to above?

**Comment by davidecantini** [comment]
@ramijarrar Unfortunately, I didn't. Due to some changes to the project in which this error was occurring, I can't guarantee if/when it'll be possible to test. For sure, if there's a chance I'll let you know (I'm also curious to know what's causing that exception). Meanwhile, if nobody else can reproduce the issue, I don't have any problem if you guys decide to re-include your PR in a future release. In case anyone will happen to report the error, you can just provide that instrumented test version right away. That's it for now. Thanks again, let's keep in touch.

**Pull request merged**
